version: 2
jobs:
  build:
    docker:
      - image: python:2.7.14

    working_directory: ~/nano

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            nosetests -v tests/
